# Generated by Django 5.2.12 on 2026-03-06 10:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('deck', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('vehicle_make', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField()),
                ('service_type', models.CharField(choices=[('wash', 'Signature Premium Wash ($89)'), ('coating', 'Advanced Ceramic Coating ($499)')], default='wash', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Vehicle Parked'), ('in-progress-wash', 'Premium Wash'), ('in-progress-coating', 'Ceramic Coating'), ('done', 'Ready for Pickup')], default='pending', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parking_zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.parkingzone')),
            ],
        ),
    ]
