# Generated by Django 5.2.12 on 2026-03-06 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='parking_zone',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='vehicle_make',
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('parking', 'Secure Airport Parking ($25/day)'), ('wash', 'Signature Premium Wash ($89)'), ('coating', 'Advanced Ceramic Coating ($499)')], default='wash', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Booking Confirmed'), ('received', 'Vehicle Received'), ('in-progress-wash', 'In Progress'), ('in-progress-coating', 'Service Completing'), ('done', 'Done')], default='pending', max_length=25),
        ),
        migrations.AddField(
            model_name='booking',
            name='airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.airport'),
        ),
        migrations.DeleteModel(
            name='ParkingZone',
        ),
    ]
