# Generated by Django 5.2.12 on 2026-03-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_airport_remove_booking_parking_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
