# Generated by Django 5.2.12 on 2026-03-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_arrival_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
