# Generated by Django 5.2.12 on 2026-03-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_booking_date_booking_pickup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('parking', 'Secure Airport Parking (₹899/starting)'), ('wash', 'Signature Premium Wash (₹1899/starting)'), ('coating', 'Advanced Ceramic Coating (₹17999/starting)')], default='wash', max_length=20),
        ),
    ]
